# show list
# POST http://localhost:5000/list   
POST https://to-do-list-madhav-kotak.herokuapp.com/list 
Content-Type: application/json

{
    "name": "Priyank"
}



###
# add an item
POST http://localhost:5000/newitem
Content-Type: application/json

{
    "name": "person 1",
    "list":"task 1"
}

###c
#remove an item
DELETE http://localhost:5000/delete/62cb06d74b2ae571ae1f9d36


